server:
  port: 8080

spring:
  main:
    web-application-type: servlet

configreloader:
  enabled: true
  enabled-annotation: config-reloader.io/enabled
  dry-run: true
  watch-mode: all  # Changed to "all" for testing - watches all deployments
